name: 03 - Workflow Runners

on:
  push:

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: |
          echo "This job is running on an Ubuntu runner.
          Runner OS: $RUNNER_OS"
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
      - shell: bash
        run: |
          echo "This job is running on a Windows runner.
          Runner OS: $RUNNER_OS"
  mac-echo:
    runs-on: macos-latest
    steps:
      - name: Show OS
        run: |
          echo "This job is running on a Mac OS runner.
          Runner OS: $RUNNER_OS""
